// @ts-nocheck — Auto-generated by Void in dev. Do NOT edit. Regenerated on every config load.



const __DEV_TRIGGER_TOKEN = "3c601bdc-31ec-43ef-9133-f1b8384bdaa9";

const __jobs = [

];

const __queues = [

];

function __json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function __authorize(request, env) {
  const internal = request.headers.get("x-void-internal");
  const dev = request.headers.get("x-void-dev-trigger");
  const expected = env?.__VOID_PROXY_TOKEN;
  if (expected) return internal === expected;
  return dev === __DEV_TRIGGER_TOKEN;
}

function __wrapMessage(m, decisions) {
  let decided = false;
  return {
    id: m.id,
    timestamp: new Date(m.timestamp),
    body: m.body,
    attempts: m.attempts,
    ack() {
      if (!decided) {
        decided = true;
        decisions.set(m.id, { action: "ack" });
      }
    },
    retry(opts) {
      if (!decided) {
        decided = true;
        decisions.set(m.id, {
          action: "retry",
          ...(opts?.delaySeconds != null ? { delaySeconds: opts.delaySeconds } : {}),
        });
      }
    },
  };
}

async function __dispatchScheduled(request, env, ctx) {
  const { cron, scheduledTime } = await request.json();
  const job = __jobs.find((j) => j.crons.includes(cron));
  if (!job) {
    return __json({ error: `No cron handler matches "${cron}"` }, 404);
  }
  const controller = { cron, scheduledTime, noRetry() {} };
  await job.handler(controller, env, ctx ?? { waitUntil() {}, passThroughOnException() {} });
  return __json({ ok: true });
}

async function __dispatchQueue(request, env) {
  const payload = await request.json();
  // Exact match only — payload.queue is the user-typed queue name from the
  // dev curl. The prod platform-side dispatch suffix-matches against
  // project-prefixed queue names, but that isn't relevant here and would
  // cause false positives between e.g. "events" and "user-events".
  const q = __queues.find((entry) => entry.name === payload.queue);
  if (!q) {
    return __json({ error: `No queue handler matches "${payload.queue}"` }, 404);
  }
  const decisions = new Map();
  const messages = (payload.messages ?? []).map((m) => __wrapMessage(m, decisions));
  const batch = {
    queue: payload.queue,
    messages,
    ackAll() {
      for (const m of messages) m.ack();
    },
    retryAll(opts) {
      for (const m of messages) m.retry(opts);
    },
  };
  try {
    await q.handler(batch, env);
  } catch (err) {
    console.error("[void] queue handler threw:", err);
    // CF queues retry the entire batch when a consumer throws, regardless
    // of any ack/retry calls made before the throw — drop partial decisions
    // so dev-mode response semantics match prod.
    return __json({ ok: false });
  }
  return __json({
    ok: true,
    ...(decisions.size > 0 ? { decisions: Object.fromEntries(decisions) } : {}),
  });
}

/**
 * If `request` is a /__void/scheduled or /__void/queue trigger, validate auth,
 * dispatch, and return a `Response`. Otherwise return null so the caller can
 * forward to the framework's normal request handling.
 */
export async function handleDevTrigger(request, env, ctx) {
  if (request.method !== "POST") return null;
  const url = new URL(request.url);
  if (url.pathname !== "/__void/scheduled" && url.pathname !== "/__void/queue") {
    return null;
  }
  if (!__authorize(request, env)) {
    return __json({ error: "unauthorized" }, 401);
  }
  if (url.pathname === "/__void/scheduled") {
    return __dispatchScheduled(request, env, ctx);
  }
  return __dispatchQueue(request, env);
}
